insert into utiliser (id_vehicule, id_voyage) values (1, 1);
insert into utiliser (id_vehicule, id_voyage) values (2, 2);
insert into utiliser (id_vehicule, id_voyage) values (3, 3);
insert into utiliser (id_vehicule, id_voyage) values (4, 4);
insert into utiliser (id_vehicule, id_voyage) values (5, 5);
insert into utiliser (id_vehicule, id_voyage) values (6, 6);
insert into utiliser (id_vehicule, id_voyage) values (7, 7);
insert into utiliser (id_vehicule, id_voyage) values (8, 8);
insert into utiliser (id_vehicule, id_voyage) values (9, 9);
insert into utiliser (id_vehicule, id_voyage) values (10, 10);
insert into utiliser (id_vehicule, id_voyage) values (11, 11);
insert into utiliser (id_vehicule, id_voyage) values (12, 12);
insert into utiliser (id_vehicule, id_voyage) values (13, 13);
-- insert into utiliser (id_vehicule, id_voyage) values (14, 14);
-- insert into utiliser (id_vehicule, id_voyage) values (15, 15);
-- insert into utiliser (id_vehicule, id_voyage) values (16, 16);
-- insert into utiliser (id_vehicule, id_voyage) values (17, 17);
-- insert into utiliser (id_vehicule, id_voyage) values (18, 18);
-- insert into utiliser (id_vehicule, id_voyage) values (19, 19);
-- insert into utiliser (id_vehicule, id_voyage) values (20, 20);
-- insert into utiliser (id_vehicule, id_voyage) values (21, 21);
-- insert into utiliser (id_vehicule, id_voyage) values (22, 22);
-- insert into utiliser (id_vehicule, id_voyage) values (23, 23);
-- insert into utiliser (id_vehicule, id_voyage) values (24, 24);
-- insert into utiliser (id_vehicule, id_voyage) values (25, 25);
-- insert into utiliser (id_vehicule, id_voyage) values (26, 26);
-- insert into utiliser (id_vehicule, id_voyage) values (27, 27);
-- insert into utiliser (id_vehicule, id_voyage) values (28, 28);
-- insert into utiliser (id_vehicule, id_voyage) values (29, 29);
-- insert into utiliser (id_vehicule, id_voyage) values (30, 30);
-- insert into utiliser (id_vehicule, id_voyage) values (31, 31);
-- insert into utiliser (id_vehicule, id_voyage) values (32, 32);
-- insert into utiliser (id_vehicule, id_voyage) values (33, 33);
-- insert into utiliser (id_vehicule, id_voyage) values (34, 34);
-- insert into utiliser (id_vehicule, id_voyage) values (35, 35);
-- insert into utiliser (id_vehicule, id_voyage) values (36, 36);
-- insert into utiliser (id_vehicule, id_voyage) values (37, 37);
-- insert into utiliser (id_vehicule, id_voyage) values (38, 38);
-- insert into utiliser (id_vehicule, id_voyage) values (39, 39);
-- insert into utiliser (id_vehicule, id_voyage) values (40, 40);
-- insert into utiliser (id_vehicule, id_voyage) values (41, 41);
-- insert into utiliser (id_vehicule, id_voyage) values (42, 42);
-- insert into utiliser (id_vehicule, id_voyage) values (43, 43);
-- insert into utiliser (id_vehicule, id_voyage) values (44, 44);
-- insert into utiliser (id_vehicule, id_voyage) values (45, 45);
-- insert into utiliser (id_vehicule, id_voyage) values (46, 46);
-- insert into utiliser (id_vehicule, id_voyage) values (47, 47);
-- insert into utiliser (id_vehicule, id_voyage) values (48, 48);
-- insert into utiliser (id_vehicule, id_voyage) values (49, 49);
-- insert into utiliser (id_vehicule, id_voyage) values (50, 50);
